### ISSUE TITLE
How Butterfly detects new state?

### ISSUE THREAD

**Issue by behnamben** [fkie-cad/butterfly#1]
What metric is used to distinguish new states? Is it a new packet or a new packet header or ...?

**Comment by pd-fkie** [comment]
It is the responsibility of a fuzzer using butterfly to extract states from the target program. There are multiple established ways to do this, e.g. by watching the values of certain global variables or by parsing server responses etc.
Once the state-data has been extracted from the target it can be fed to the  `StateObserver`.
The `StateObserver` hashes the incoming data and when a hash value has never been seen before, the target has entered a new state and the input is retained.
A fuzzer can feed any kind of rust types that are hashable to the observer.

Does this answer your question?

**Comment by behnamben** [comment]
Yes thank you.
